### GET All - admin
GET /api/v1/pets HTTP/1.1
Host: localhost:8080
Authorization: Basic YWRtaW46YWRtaW4=

### GET All - user
GET /api/v1/pets HTTP/1.1
Host: localhost:8080
Authorization: Basic dXNlcjp1c2Vy

### GET All - anonymous
GET /api/v1/pets HTTP/1.1
Host: localhost:8080

### POST - admin
POST /api/v1/pets HTTP/1.1
Content-Type: application/json
Host: localhost:8080
Authorization: Basic YWRtaW46YWRtaW4=
{
	"id": "jack",
	"animal": "dog",
	"name": "Jack",
	"ownerName": "Melina"
}

### POST - user
POST /api/v1/pets HTTP/1.1
Content-Type: application/json
Host: localhost:8080
Authorization: Basic dXNlcjp1c2Vy
{
	"id": "jack",
	"animal": "dog",
	"name": "Jack",
	"ownerName": "Melina"
}

### POST - anonymous
POST /api/v1/pets HTTP/1.1
Content-Type: application/json
Host: localhost:8080
{
	"id": "jack",
	"animal": "dog",
	"name": "Jack",
	"ownerName": "Melina"
}

### PUT - admin
PUT /api/v1/pets/jack HTTP/1.1
Content-Type: application/json
Host: localhost:8080
Authorization: Basic YWRtaW46YWRtaW4=
{
	"id": "jack",
	"animal": "dog",
	"name": "Jackie",
	"ownerName": "Melina"
}

### PUT - user
PUT /api/v1/pets/jack HTTP/1.1
Content-Type: application/json
Host: localhost:8080
Authorization: Basic dXNlcjp1c2Vy
{
	"id": "jack",
	"animal": "dog",
	"name": "Jackie",
	"ownerName": "Melina"
}

### PUT - anonymous
PUT /api/v1/pets/jack HTTP/1.1
Content-Type: application/json
Host: localhost:8080
{
	"id": "jack",
	"animal": "dog",
	"name": "Jackie",
	"ownerName": "Melina"
}

### DELETE - admin
DELETE /api/v1/pets/jack HTTP/1.1
Host: localhost:8080
Authorization: Basic YWRtaW46YWRtaW4=
